-- Generated by Oracle SQL Developer Data Modeler 20.4.1.406.0906
--   at:        2021-05-04 18:47:41 EEST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c


CREATE TABLE IF NOT EXISTS car (
    brand            character varying(100) NOT NULL,
    model            character varying(100) NOT NULL,
    fuel             character varying(100),
    engine_capacity  SMALLINT,
    color            character varying(100)
);

ALTER TABLE car ADD CONSTRAINT car_pk PRIMARY KEY ( brand,
                                                    model );

CREATE TABLE IF NOT EXISTS color (
    color_name character varying(50) NOT NULL
);

ALTER TABLE color ADD CONSTRAINT color_pk PRIMARY KEY ( color_name );

CREATE TABLE IF NOT EXISTS fuel (
    type character varying(100) NOT NULL
);

ALTER TABLE fuel ADD CONSTRAINT fuel_pk PRIMARY KEY ( type );

CREATE TABLE IF NOT EXISTS operations (
    oper_code  SMALLINT NOT NULL,
    oper_name  text
);

ALTER TABLE operations ADD CONSTRAINT operations_pk PRIMARY KEY ( oper_code );

CREATE TABLE IF NOT EXISTS request (
    oper_code       SMALLINT NOT NULL,
    req_date          DATE,
    car_brand       character varying(100),
    car_model       character varying(100),
    department      INTEGER NOT NULL,
    customer_type   character varying(10),
    new_reg_number  character varying(20)
);

ALTER TABLE request
    ADD CONSTRAINT request_pkv1 PRIMARY KEY ( oper_code,
                                              req_date,
                                              department,
                                              car_brand,
                                              car_model );

CREATE TABLE IF NOT EXISTS service_center (
    dep_code  INTEGER NOT NULL,
    dep_name  character varying(50)
);

ALTER TABLE service_center ADD CONSTRAINT service_center_pk PRIMARY KEY ( dep_code );

ALTER TABLE car
    ADD CONSTRAINT car_color_fk FOREIGN KEY ( color )
        REFERENCES color ( color_name );

ALTER TABLE car
    ADD CONSTRAINT car_fuel_fk FOREIGN KEY ( fuel )
        REFERENCES fuel ( type );

ALTER TABLE request
    ADD CONSTRAINT request_car_fk FOREIGN KEY ( car_brand,
                                                car_model )
        REFERENCES car ( brand,
                         model );

ALTER TABLE request
    ADD CONSTRAINT request_operations_fk FOREIGN KEY ( oper_code )
        REFERENCES operations ( oper_code );

ALTER TABLE request
    ADD CONSTRAINT request_service_center_fk FOREIGN KEY ( department )
        REFERENCES service_center ( dep_code );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE IF NOT EXISTS                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             11
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLE IF NOT EXISTSSPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
