DROP TABLE IF EXISTS car CASCADE;

DROP TABLE IF EXISTS color CASCADE;

DROP TABLE IF EXISTS fuel CASCADE;

DROP TABLE IF EXISTS operations CASCADE;

DROP TABLE IF EXISTS request CASCADE;

DROP TABLE IF EXISTS service_center CASCADE;